### ISSUE TITLE
[meta] Report individual issues detailing each of a set of proposed check modifications considering variable fonts

### ISSUE THREAD

**Issue by laerm0** [googlefonts/fontbakery#2047]
~~(this issue is incomplete, I'll edit and ping you @felipesanches when I have a pretty comprehensive list of test that can be tweaked for when fb is testing a variable font)~~

- [ ]  contour counts
- [ ]  canonical naming
- [ ]  `com.google.fonts/check/has_ttfautohint_params`
- [ ]  FontForge validation (pretty sure this breaks on VF)
- [ ]  ttx roundtrip looks like it also fails on VF

**Comment by felipesanches** [comment]
alright, Thanks!

**Comment by laerm0** [comment]
@felipesanches I think the list I have above is pretty final. I'll further research the last two and let you know.

**Comment by laerm0** [comment]
Yep, FontForge can't handle VF. Hard to tell about ttx, though. It crashes on VFs I throw at it, but I saw [an issue](https://github.com/fonttools/fonttools/issues/1306) that says maybe it's hint code that does it...? @anthrotype, any thoughts? Should I send you this font and error?

**Comment by felipesanches** [comment]
@laerm0, could you please break this issue into 5 independent issues providing details for each required modification? (and also why such modifications are needed)

**Comment by laerm0** [comment]
Sure thing, Felipe.

**Comment by felipesanches** [comment]
Feel free to close this issue immediately after all 5 new issues are reported. Thanks!

**Comment by felipesanches** [comment]
@laerm0 please report individual issues for the problems described here.

I can't address everything at once and without more details descriptions of the problems and rationales. Please take some time to improve those requests.

For now I will move this into the "Someday Maybe" milestone.

**Comment by davelab6** [comment]
@laerm0 please split into separate issues :)

**Comment by laerm0** [comment]
It looks like @felipesanches has already made these changes, so this issue is now entirely irrelevant. :)
