### ISSUE TITLE
diacritic check summary 

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#3319]
I try to reformulate what was said in the meeting yesterday for the diacritic check.
I'll update this to-do with more details

- [ ] Diacritics are not off an approximative range of alignment (#3293)
- [ ] Diacritics are used consistently (#3296)
- [ ] Comb accents are used in accented composites (#1861)
- [ ] Comb accents have `_top` and `top` anchors to allow multiple combining accents

**Comment by felipesanches** [comment]
it is OK to have a summary issue like this to track progress on a set of things. But it's important that the details are discussed in the individual issues for each of these new check proposal. Please post an issue for `"WARN top-comb accents have _top and top anchors to allow multiple combining accents"`

**Comment by vv-monsalve** [comment]
> [ ] **WARN** Diacritics are used consistently (#3296)

I would propose a FAIL status for this one.

**Comment by davelab6** [comment]
@RosaWagner mentioned on chat "For the problem with GDEF table and confusion between legacy accents and comb accents, I can confirm that fixing Radio Canada is fixing this display issue on the API. It seems therefore more ans more important to implement [this issue]"

**Comment by RosaWagner** [comment]
FYI, all the Tiro Indic families have a GDEF table warning;

⚠ WARN: Check mark characters are in GDEF mark glyph class. ([com.google.fonts/check/gdef_mark_chars](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_mark_chars))
⚠ WARN The following mark characters could be in the GDEF mark glyph class:
acutecomb (U+0301), brevebelowcomb (U+032E), brevecomb (U+0306), candrabinducomb (U+0310), caroncomb (U+030C), cedillacomb (U+0327), circumflexcomb (U+0302), commaaccentcomb (U+0326), dieresisbelowcomb (U+0324), dieresiscomb (U+0308) and 9 more.

This is the consequences of such issue in GF:
<img width="1090" alt="Capture d’écran 2022-05-18 à 10 59 04" src="https://user-images.githubusercontent.com/12222436/169001776-2cb85525-bae4-45af-8750-c6db1f38899a.png">

@davelab6 I don't know if the warn should be a fail, or if GF should stop displaying glyphs that are actually not encoded in the font. 

cc @vv-monsalve @m4rc1e

**Comment by RosaWagner** [comment]
Adding this issue to bump up priority on this list of check, this is the example of a font that shouldn't have passed QA: https://github.com/google/fonts/issues/6226
