### ISSUE TITLE
[META] Tasks for Felipe

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#658]
List of current top-priority issues:

- [x] #573 [metadata-vs-api] category comparison (most important)
- [x] #616 deduplicate lines (This would be great. This is really annoying :)
- [x] #624 fix gasp table check
- [x] #674 fix crash: genmetadata.py: TypeError: object of type 'bool' has no len()
- [x]  #676 (WebPanel for CoinyTest fails to load properly) that is... make the web app work once again.
- [x] Set up a fork of Catamaran baked from TTF delivery files (https://github.com/felipesanches/Catamaran-Tamil-Tests)
- [x] Write a proposal for a clean rewrite; the issues in https://github.com/googlefonts/fontbakery/milestones/2.0 may be relevant (#667)
- [x] #684 Font Classification Tool
- [x] #696 Stop making menu files
- [x] #741 Fix family name fixer
- [x] #697 Don't run upstream tests when they are not needed
- [x] #693 Fix many small issues
- [x] #748 Fix family name fixed for PID=1 items
- [x] ~~#611~~ #723, #724 web: Fix 404 properly.
- [x] https://github.com/googlefonts/fontbakery/issues/241
- [x] #666 Support fontmake to build your fork of Catamaran from the glyph source file

- [x] Get https://github.com/fontforge/fontforge/pull/2467 ready to merge
- [x] ~~#655 [METADATA.pb] This is another place where the json files are still expected~~ (postponed)

**Comment by davelab6** [comment]
Cool :) I think in future its better we can just make the list of such issues by only assigning them to you when they are up for working on soon, and tagging with priorities. So, for me,

- [ ] [Review all issues assigned to me](https://github.com/googlefonts/fontbakery/issues?q=assignee%3Adavelab6+is%3Aopen) and close or tag all issues with 'P0' to 'P4' priority tags (and maybe unassign)
- [ ] [Review all issues assigned to no one](https://github.com/googlefonts/fontbakery/issues?q=is%3Aopen+no%3Aassignee) and close or tag all issues with 'P0' to 'P4' priority tags
- [ ] [Review all issues assigned to felipe](https://github.com/googlefonts/fontbakery/issues?q=assignee%3Adavelab6+is%3Aopen) and close or tag all issues with 'P0' to 'P4' priority tags (and maybe unassign)

**Comment by davelab6** [comment]
> Attempts were:
> 
> * fontbakery on Catamaran from source
> * fontbakery on Catamaran from binaries
> * fontbakery on Coiny from sfd source on Travis
> * fontbakery on Coiny from sfd source on my local machine
> * issues with a couple newly found bugs in the toolchain

Great! 

Postpone building from source for now; Catamaran has binary TTFs that we should start with. I've updated the above live to reflect this.

> Catamaran has sources in Glyphs file format, which we don't support in fontbakery. 

Right, pending fontmake integration 

> We could only run the tests and fixers starting from the binaries of TTF hinted and unhinted fonts. But with the purpose of testing the whole build / test toolchain of fontbakery, it would be good to work with a project that provides sources in sourceforge file format. So I chose to really deal with Coiny today  (as was initially planned) instead of with Catamaran.

Per https://github.com/googlefonts/fontbakery/blob/master/BRIEF.md I would like to focus on the first section's test/fix subset of the toolchain until that is solid.

> Travis has been presenting bad behaviour recently. Indeed, the job did not run yet. So, I've been running fontbakery locally for tests.

Cool

> While running fontbakery-build.py on the Coiny project, I detected 2 new bugs:
> 
> (1) something is wrong with the 'gaspRange[65535] value is not 15' fixer. I need some guidance from you here about what is the meaning of this text and fixer. I quickly looked at the spec, but was unable to understand what's the purpose here.

I added the relevant issue to the above list and updated it

> I commented out this portion of the test to see if the rest of the toolchain is OK.
> Then I got this other problem:
> 
> (2) 
> required: FAIL: bakery_lint/fonttests/test_ttf.py: CheckFontAgreements.test_latin_file_exists():  GF requires a latin subset, so we check that font file exists : False is not true
> required: FAIL: bakery_lint/fonttests/test_ttf.py: CheckFontAgreements.test_menu_file_exists():  GF requires a menu subset, so we check that font file exists : False is not true
> Error: object of type 'bool' has no len()
> 
> I haven't looked more carefuly on this one, though.

Right, that is bad organization of the code, I think; the ttf check should only be testing the integrity of the ttfs, and the checks for required subset files are (a) now an obsolete requirement because they are not generated offline and stored in git and (b) before they became unneeded the checks should have lived in the metadata checker.

**Comment by felipesanches** [comment]
We're moving to a new issue at https://github.com/googlefonts/fontbakery/issues/767

This one will be closed now (may be reopened in the future if we need to deal with it again).
