### ISSUE TITLE
[META] Tasks for Dave

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#662]
In future we should set priorities and assign people using the github issue tracker's features for that: only assigning issues to people when they are going to work on that issue soon; and tagging all issues with a  priority tag.
- [x] Review existing tag label strings and add P0-4 ones
- [x] Update CONTRIBUTING
- [x] Start #661 
- [x] https://github.com/googlefonts/fontbakery/issues/747
- [ ] [Review all issues assigned to me](https://github.com/googlefonts/fontbakery/issues?q=assignee%3Adavelab6+is%3Aopen) and close or tag all issues with 'P0' to 'P4' priority tags (and maybe unassign)
- [x] [Review all issues assigned to no one](https://github.com/googlefonts/fontbakery/issues?q=is%3Aopen+no%3Aassignee) and ensure they are in milestones
- [ ] [Review all issues assigned to felipe](https://github.com/googlefonts/fontbakery/issues?q=assignee%3Afelipesanches+is%3Aopen) and close or tag all issues with 'P0' to 'P4' priority tags (and maybe unassign)
- [ ] Make issues for the 2.0.0 milestone that form a technical roadmap.

**Comment by simoncozens** [comment]
This is seven years old and Dave is probably too busy to be doing this stuff right now. ;-)
